---
author: "Artha Finance SA"
classoption: landscape
geometry: margin=0.5cm
header-includes: \usepackage{fancyhdr} \pagestyle{fancy}
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)


```



```{r tidy data, echo= FALSE, include= FALSE}


library(data.table)

timbre <- fread("ibTimbre.csv")

setorder(timbre, OrderTime, Description, -ClientId)

# remove and change column names and reorder columns
#timbre[, Symbol:= NULL]
# 
colnames(timbre) <- c("OrderTime", "AssetClass", "Nom", "Isin", "Date.Op", "Dev", "Type", 
                      "Nominal", "Prix", "Proceeds", "Client", "Cours", 
                      "Soumis CH", "Soumis ETR", "Non Soumis", "cliNbr")

#add Dom of CURRENT clients
timbre[Client != "Interactive Brokers", Dom:="CH"]
timbre[Client == "Interactive Brokers", Dom:="INS"]

# add number of operation
timbre[, No:= .GRP, by= c("OrderTime", "Nom")] 

# group data to fit A4 page ! change %/% to match length
timbre[, Grp:= c(cliNbr[1], rep(0,.N - 1L)), by= No]
#timbre[, Grp:= cumsum(Grp) %/% 57 + 1]
timbre[, Grp:= ceiling(cumsum(Grp)/ 60)]

# remove some columns
timbre$OrderTime <- timbre$cliNbr <- timbre$Proceeds <- timbre$AssetClass <- NULL

timbre <- timbre[, c("Grp", "No", "Date.Op", "Type","Nominal", "Nom", "Isin", "Prix",
                     "Dev", "Cours" ,"Client", "Dom", "Soumis CH", "Soumis ETR",
                      "Non Soumis")]

# calc totals by Group and add empty columns to match timbre structure
subTotal <- timbre[, lapply(.SD, sum, na.rm= TRUE), 
                   by= "Grp",
                   .SDcols= c("Soumis CH", "Soumis ETR", "Non Soumis")]

subTotal[, ':=' ('No'= 0L,     Date.Op= "", Type= "", 
                 Nominal=  0L, Nom= "",     Isin= "", 
                 Prix= 0,      Dev= "",     Cours= 0, 
                 Client= "Contre valeur Totale", 
                 Dom= "")]

# add empty first line for clear printing
empty <- copy(subTotal)
set(empty, i= NULL, j= c(colnames(empty)[c(-1, -6)]), value= NA)

# calc amounts TimbreDue
droits <- subTotal[, .(`Soumis CH`  * 0.075 / 100,
                       `Soumis ETR` * 0.15  / 100,
                       0), 
                   by= "Grp"]

colnames(droits) <- c("Grp", "Soumis CH", "Soumis ETR", "Non Soumis")

droits[, ':=' ('No'= 0L,     Date.Op= "", Type= "", 
               Nominal=  0L, Nom= "",     Isin= "", 
               Prix= 0,      Dev= "",     Cours= 0,
               Client= "Droits négociation TimbreDus", 
               Dom= "")]


setcolorder(droits,   colnames(timbre))
setcolorder(subTotal, colnames(timbre))
setcolorder(empty,    colnames(timbre))


printData <- do.call(rbind, list(timbre, empty, subTotal, droits, empty))

printData[, Date.Op:= as.Date(Date.Op)]
printData <- printData[Date.Op >= as.Date("2019-06-30") & 
                     Date.Op <= as.Date("2019-09-30"),]

printData[, Date.Op:=  as.character(strftime(
    as.Date(Date.Op, "%Y-%m-%d"), "%d-%m-%Y"))]

printData[grepl("Contre", Client), Date.Op:= NA ]
printData[grepl("Droits", Client), Date.Op:= NA ]

printData[is.na(Client), Date.Op:= NA ]

printData[!grepl("Interactive|Picte", Client), ':=' (No=      NA,
                                               Date.Op= NA,
                                               Nom=     NA,
                                               Isin=    NA)]
# remove zero's
printData[printData==0] <- NA

#split data per group 
printData <- split(printData, by= "Grp", keep.by= FALSE)


```


```{r xtable, results="asis", echo=FALSE}

library(xtable)

options(xtable.type= "latex",
        tabular.environment = "longtable",
        xtable.comment = FALSE,
        xtable.caption.width="p{30}",
        xtable.include.rownames= FALSE,
        xtable.scalebox= 0.7,
        xtable.format.args = list(big.mark = "'"))

bold <- function(x) {paste('{\\textbf{',x,'}}', sep ='')}


for (g in 1:length(printData)) {

    header <- data.table(matrix(c(strrep("-", 112),
                                  "Artha Finance SA",
                                  "Interactive Brokers (UK) Ltd, Ldn - Pictet, Lux",
                                  NA,

                                  "REGISTRE DES NEGOCIATIONS",
                                  NA,
                                  NA,
                                  NA,

                                  strrep("-", 112),
                                  as.character(strftime(Sys.Date(),
                                                        "%d %B %Y")),
                                  paste("Page: ", g),
                                  NA),
                                4, 3))


    print(xtable(header, align=  c("llcr")),
          include.colnames = FALSE,
          hline.after= NULL,
          sanitize.text.function= bold,
          table.placement = "t")

    tab <- xtable(printData[[g]],
                  NA.string= '',
                  digits= c( 0, 0, 0, 0, 0, 0, 0, 3, 0, 4, 0, 0, 2, 2, 2),
                  align=  c("l||cc|crp{9cm}p{2.5cm}r|cr|lc||rr|r||"))

    lines <- printData[[g]][grepl("Interacti|Pict", Client), which= TRUE]

    print(tab,
          hline.after= c(-1, 0,
                         lines,
                         nrow(tab))

          ,sanitize.colnames.function= bold
          #, table.placement= "t"
    )

}

total  <- subTotal[, lapply(.SD, sum, na.rm= TRUE),
                   .SDcols= c("Soumis CH", "Soumis ETR", "Non Soumis")]

total[, Totaux:= "Cumul trimestriel"]

TimbreDu <- droits[, lapply(.SD, sum, na.rm= TRUE),
                   .SDcols= c("Soumis CH", "Soumis ETR", "Non Soumis")]

TimbreDu[, Totaux:= "Droits de négociations dûs"]

total <- rbind(total, TimbreDu)
total <- rbind(total, total[1])

setcolorder(total, c(4, 1, 2, 3))

TimbreDu <- total[2, round((`Soumis CH` + `Soumis ETR`) / 0.05) * 0.05]

total[3, ':=' (Totaux= "Total a payer",
               `Soumis CH`=  0,
               `Soumis ETR`= 0,
               `Non Soumis`= TimbreDu)]

total <- xtable(total,
                digits= c( 0, 0, 2, 2, 2),
                align=  c("l||l|rr|r||"))

print(total, hline.after= c(-1, 0, nrow(total) - 1, nrow(total)),
      sanitize.colnames.function = bold)


# print totals by clients for control
client <- timbre[!grepl("Interact|Pict", Client), 
                 .(sum(`Soumis CH` +`Soumis ETR`),
                   sum((`Soumis CH` * 0.075 /100) +
                           (`Soumis ETR` * 0.15 /100))), 
                 by= Client]

colnames(client) <- c("Client", "Cumul", "Total")

client <- rbind(client, client[1])

client[.N, ':=' (Client= "Total à payer",
                Cumul= NA,
                Total= total[3,4])]

client <- xtable(client,
                 digits= c( 0, 0, 0, 2),
                 align=  c("l||l||r|r||"))

print(client, hline.after= c(-1, 0, nrow(client) - 1, nrow(client)),
      sanitize.colnames.function = bold)


```


